# Generated by Django 4.2.6 on 2023-10-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=100)),
                ('is_expert', models.BooleanField(default=False)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
